app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root 'ranks#index'
  resources :training, only: %i(index new create destroy update show) do
    get :complete
  end
  resources :sessions, only: %i(new create destroy)
  resources :users, only: %i(new create) do
    get :mypage
  end
  resources :goods, only: %i() do
    get :search, on: :collection
    post :search_list, on: :collection
  end
  resources :favorite, only: %i(create destroy)
  
  get '/:genre' => 'ranks#index'
  get '/:genre/:id' => 'ranks#show'


end

app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id             :integer          not null, primary key
#  user_id      :integer            not null
#  rank_id      :integer
#  created_at
#  updated_at

class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :rank, optional: true

  validates :user_id, {presence: true}
end

app/app/models/rank.rb
# == Schema Information
#
# Table name: devices
#
#  id             :integer          not null, primary key
#  rank           :integer
#  itemName       :string
#  itemPrice      :integer
#  reviewAverage  :decimal
#  mediumImageUrls:string
#  itemCaption    :text
#  itemUrl      :string 
#  genre      :string 
# 

class Rank < ApplicationRecord
  belongs_to :users, optional: true
  has_many :favorites

  GENRES = {
    ranks: 100984,
    food: 111903,
    drink: 204673,
    sweets: 204655,
    suporters: 204675,
    equipments: 204674,
    others: 101885
  }
end

app/app/models/training.rb
class Training < ApplicationRecord
  belongs_to :users, optional: true
end

app/app/models/user.rb
# == Schema Information
#
# Table name: devices
#
#  id                        :integer          not null, primary key
#  name                      :string           not null
#  email                     :integer          not null, uniqueness: true
#  password_digest           :string           not null, length:{minimum: 8} 
#  

class User < ApplicationRecord
  has_secure_password

  has_many :ranks
  has_many :trainings
  has_many :favorites
  has_many :favorite_ranks, through: :favorites, source: :rank

  validates :name , {presence: true}
  validates :email, {uniqueness: true, presence: true}
  validates :password, {length: {minimum: 8}}
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :set_current_user
  
  
  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to(new_session_path)
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to(user_mypage_path(@current_user.id))
    end
  end
end

app/app/controllers/favorite_controller.rb
class FavoriteController < ApplicationController

  def create
    @like = Favorite.new(
      user_id: params["user_id"], 
      rank_id: params["rank_id"], 
    )
    @like.save
    flash[:notice] = "お気に入り登録しました"
    redirect_to("/rank/#{params["rank_id"]}")
  end


  def destroy
    @like = Favorite.find_by(
      user_id: params["user_id"], 
      rank_id: params["rank_id"], 
    )
    @like.destroy
    flash[:notice] = "お気に入り登録を解除しました"
    redirect_to("/ranks/#{params["rank_id"]}")
  end
end

app/app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def search
  end

  def search_list
    if params[:keyword]
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword], genreId: 100984)
    end  
  end
end

app/app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_item, only: [:show]
  
  def index

    genre = Rank::GENRES
    @rankings = RakutenWebService::Ichiba::Genre[genre[:"#{params[:genre]}"]].ranking.page(params[:page])
    
    ranking_array = []
    @rankings.each do |ranking|
      rank = Rank.new(
        rank: ranking["rank"], 
        itemName:ranking["itemName"], 
        itemPrice:ranking["itemPrice"], 
        itemCaption:ranking["itemCaption"], 
        reviewAverage:ranking["reviewAverage"], 
        mediumImageUrls:ranking["mediumImageUrls"][0], 
        itemUrl: ranking["itemUrl"],
        genre: "#{params[:genre]}"
      );

      rank.save
      ranking_array.push(rank)
    end

    @rankings = Kaminari.paginate_array(ranking_array, total_count: 100).page(params[:page])
    @item = Rank.find_by(genre: params[:genre])
  end

  def show
    @favorite = Favorite.new
  end



  private
  def set_item
    @item = Rank.find_by(id: params[:id])
  end
end

app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, {only: [:destroy]}
  before_action :forbid_login_user, {only: [:new, :create]}

  def new
  end

  def create 
    @user = User.find_by(email: params[:email]);
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "ログインに成功しました"
      redirect_to(user_mypage_path(@user.id))
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      flash[:notice] = "ログインに失敗しました"
      render("new")
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to(new_session_path)
  end
end

app/app/controllers/training_controller.rb
class TrainingController < ApplicationController
  before_action :set_training

  def index
    @trainings = Training.all
  end

  def show
  end

  def new
  end

  def create
    training = Training.new(tasks: params[:tasks], content: params[:content], limit: params[:limit], completed: params[:completed])
    if training.save
      flash[:notice] = "トレーニングスケジュールを追加しました。"
      redirect_to(training_index_path(@current_user.id))
    else
      flash[:notice] = "トレーニングスケジュールを出来ませんでした。"
      render("new")
    end
  end

  def update
    if @training.update(training_params)
      flash[:notice] = "トレーニングスケジュールを更新しました。"
      redirect_to(training_index_path(@current_user.id))
    else
      flash[:notice] = "トレーニングスケジュールを更新出来ませんでした。"
      render("show")
    end
  end

  def destroy
    if @training.destroy
      flash[:notice] = "スケジュールを削除しました。"
      redirect_to(training_index_path(@current_user.id))
    else
      flash[:notice] = "スケジュールを削除出来ませんでした。"
      render("index")
    end
  end

  def complete
    @training.completed = 1
    flash[:notice] = "トレーニングお疲れさまです。完了しました。"
    redirect_to(training_index_path(@current_user.id))
    # @training.completed = 0
    # flash[:notice] = "トレーニングが完了していません。"
    # redirect_to(training_index_path(@current_user.id))
  end

  private
  def set_training
    @training = Training.find_by(id: params[:id])
  end

  def training_params
    params.permit(:tasks, :content, :limit, :completed)
  end
end

app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:mypage]}
  before_action :forbid_login_user, {only: [:new, :create]}

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "新規登録完了しました"
      redirect_to(user_mypage_path(@user.id))
    else
      flash[:notice] = "新規登録に失敗しました"
      render('new');
    end
  end

  def mypage 
    @user = User.find_by(id: @current_user);
    @favorite_ranks = @user.favorite_ranks
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/app/helpers/goods_helper.rb
module GoodsHelper
end

app/app/helpers/ranks_helper.rb
module RanksHelper
end

app/app/helpers/sessions_helper.rb
module SessionsHelper
end

app/app/helpers/training_helper.rb
module TrainingHelper
end

app/app/helpers/users_helper.rb
module UsersHelper
end

app/app/views/goods/search.html.slim
section.goods-search
  .goods-search__texts
    p.goods-search__texts__text
      | 商品名
  .goods-search__input
    = form_with url: search_list_goods_path, name: "keyword", class: "input", local: true do |f|
      = f.text_field :keyword
      button.search-btn[type="submit" name="commit" value="" data-disable-with=""]
        | 検索

app/app/views/goods/search_list.html.slim
= render 'layouts/category'
.search-result
  p.search-result__text
    | 検索結果: 
    span.search-result__genre
      = params[:keyword]
section.index
  - @items.each do |item|
    = link_to( item.url, :target=>["_blank"]) do
      .index__contents
        .index__contents__content
          .index__contents__content__images
            = image_tag item.medium_image_urls[0], class: 'index__contents__content__images__image'
          .index__contents__content__texts
            h2.index__contents__content__texts__text
              = truncate(item.name, length:60)
            .price_review
              p.index__contents__content__texts__price
                span.fee
                  = item.price
                | 円(税込)
              p.index__contents__content__texts__review
                = item.review_average
                span.reviewMax
                  | /5

app/app/views/layouts/_category.html.slim
section.l-header__main
  h1.l-header__main__heading.slide
    | 体型が変われば、人生が変わる
  a.l-header__main__btn
    | Genre
section.category
  section.category__contents
    = link_to '/food' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/food.jpg"]
        h3.category__contents__content__heading
          | Food
    = link_to '/drink' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/drink.jpg"]
        h3.category__contents__content__heading
          | Drink
    = link_to '/sweets' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/sweets.jpg"]
        h3.category__contents__content__heading
          | Sweets
    = link_to '/suporters' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/suporter.jpg"]
        h3.category__contents__content__heading
          | Suporter
    = link_to '/equipments' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/equipment.jpg"]
        h3.category__contents__content__heading
          | Equipment
    = link_to '/others' do
      .category__contents__content
        img.category__contents__content__image[src="/category_images/others.jpg"]
        h3.category__contents__content__heading
          | Others

app/app/views/layouts/_flash.html.slim
- if flash[:notice]
  .flash
    = flash[:notice]

app/app/views/layouts/_footer.html.slim
footer.l-footer
  p.l-footer__text
    small
      | ©️ 2020 ZeroCalo.

app/app/views/layouts/_header_top.html.slim
header.l-header
  section.l-header__top
    .l-header__top__left
      = link_to("/ranks", data: {"turbolinks" => false}) do
        h2.l-header__top__left__heading
          i.fas.fa-apple-alt
          | ZeroCalo
    .l-header__top__right
      .l-header__top__right__bars
        i.fas.fa-bars.menu
      .l-header__top__right__texts
        nav.l-header__top__right__texts__nav
          p.l-header__top__right__texts__nav__heading
            i.fas.fa-crown
            | Ranking
          ul.l-header__top__right__texts__nav__lists
            = link_to( "/ranks") do
              li.l-header__top__right__texts__nav__lists__list
                | ALL
            = link_to( "/food") do
              li.l-header__top__right__texts__nav__lists__list
                | FOOD
            = link_to( "/drink") do
              li.l-header__top__right__texts__nav__lists__list
                | DRINK
            = link_to( "/sweets") do
              li.l-header__top__right__texts__nav__lists__list
                | SWEETS
            = link_to( "/suporters") do
              li.l-header__top__right__texts__nav__lists__list
                | SUPORT
            = link_to( "/equipments") do
              li.l-header__top__right__texts__nav__lists__list
                | EQUIPMENT
            = link_to( "/others") do
              li.l-header__top__right__texts__nav__lists__list
                | OTHERS
        = link_to search_goods_path do
          .l-header__top__right__texts__lists
            p.l-header__top__right__texts__lists__heading
              | Goods Search
        - if session[:user_id]
          = link_to training_index_path(@current_user.id) ,{method: "get"} do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Training
        - if session[:user_id]
          = link_to session_path(@current_user.id) ,{method: "delete"} do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Logout
          = link_to user_mypage_path(@current_user.id) do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Mypage
        - else
          = link_to new_user_path do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Sign up
          = link_to new_session_path do
            .l-header__top__right__texts__lists
              p.l-header__top__right__texts__lists__heading
                | Login

app/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script[src="https://kit.fontawesome.com/76b7c2052c.js" crossorigin="anonymous"]
    meta[name="viewport" content="width=device-width,initial-scale=1.0"]
  body
    .container
      = render 'layouts/header_top'
      .contents
        = render 'layouts/flash'
        = yield
      = render 'layouts/footer'
      div

app/app/views/ranks/index.html.slim
= render 'layouts/category'
section.goods_index
  - @rankings.each do |ranking|
    = link_to( "#{@item.genre}/#{@item.id + ranking[:rank] - 1}") do
      .ranks
        p.ranks__rank
          = ranking[:rank]
          span.ranks__i
            | 位
      .index__contents
        .index__contents__content
          .index__contents__content__images
            = image_tag ranking[:mediumImageUrls], class: 'index__contents__content__images__image'
          .index__contents__content__texts
            h2.index__contents__content__texts__text
              = truncate(ranking[:itemName], length:60)
            .price_review
              p.index__contents__content__texts__price
                span.fee
                  = ranking[:itemPrice]
                | 円(税込)
              p.index__contents__content__texts__review
                = ranking[:reviewAverage]
                span.reviewMax
                  | /5
= paginate @rankings, total_pages: 10

app/app/views/ranks/show.html.slim
section.show
  .show__contents
    .show__contents__images
      = image_tag @item.mediumImageUrls, class: 'show__contents__images__image'
    .show__contents__texts
      h2.show__contents__texts__heading
        = @item.itemName
      .price_review
        p.show__contents__texts__price
          span.fee
            = @item.itemPrice
          | 円(税込)
          span.send-fee
            | 送料無料
        - if session[:user_id] != nil
          - if Favorite.find_by(user_id: @current_user.id, rank_id: @item.id)
            = form_with url: "/favorite/#{@item.id}",method: "delete", local: true do |f|
              = f.hidden_field :rank_id, value: @item.id
              = f.hidden_field :user_id, value: @current_user.id
              button.favorite-button[type="submit" name="commit" value="" data-disable-with=""]
                p.show__contents__texts__favorite
                  i.fas.fa-thumbs-up
          - else
            = form_with url: "/favorite", method: "post", local: true do |f|
              = f.hidden_field :rank_id, value: @item.id, commit: "submit"
              = f.hidden_field :user_id, value: @current_user.id, commit: "submit"
              button.favorite-button[type="submit" name="commit" value="" data-disable-with=""]
                p.show__contents__texts__favorite
                  i.far.fa-thumbs-up
        p.show__contents__texts__review
          = @item.reviewAverage
          span.reviewMax
            | /5
      p.show__contents__texts__info
        = @item.itemCaption
  .rakuten
    = link_to("#{@item.itemUrl}", :target=>["_blank"]) do
      .rakuten__btn
        |  楽天詳細ページに行く 
.return
  = link_to( "/#{@item.genre}", data: {"turbolinks" => false}) do
    .return__btn
      |  ランキングに戻る 

app/app/views/training/_training-contents_header.html.slim
.training-contents_header
    .training-contents_heading
      h2.training-contents_heading_content.heading
        | Tarining List
    .training-contents_text
      p.training-contents_text_content
        | 日々のトレーニングのスケジュールを管理しましょう。
    .training-contents_btn
      = link_to(new_training_path) do
        .new-btn
          | CREATE NEW TRAINING

app/app/views/training/_training_list.html.slim
.training-contents_index
  table.table 
    tr
      th State
      th Training
      th contents
      th Limit
    - for training in @trainings
      tr
        - if training.completed == 0
          td.state.incomplete 
            | Incomplete
        - elsif training.completed == 1
          td.state.complete 
            | Complete
        td = training.tasks
        td = truncate(training.content, length:20)
        td = training.limit
        td
          = link_to  training_complete_path(training.id), class: 'training-btn'
            i.fas.fa-check-circle.complete-btn
        td
          = link_to  training_path(training.id), class: 'training-btn', method: :get
            i.fas.fa-info-circle.edit-btn
        td
          = link_to  "/training/#{training.id}", class: ' training-btn', method: :delete
            i.fas.fa-times-circle.delete-btn
      

app/app/views/training/index.html.slim
section.training-contents.index
  = render partial: 'training/training-contents_header'
  = render partial: 'training/training_list'
  
  

app/app/views/training/new.html.slim
section.new-tasks.index
  .new-tasks_heading
    h2.new-tasks_heading_content.heading
      | NEW TRAINING

  = form_with  url: "/training" ,class: "form_class", local: true do |f|
    = f.label :tasks, 'トレーニング名'
    = f.text_field :tasks, id: "tasks"
    = f.label :content, 'トレーニング内容'
    = f.text_area :content, id: "content"
    = f.label :limit, '日付'
    = f.date_field :limit, id: "limit"
    = f.hidden_field :completed, :value => 0, id: 'task_completed'
    = f.submit "新規登録", class: "submit"

app/app/views/training/show.html.slim
section.new-tasks.index
  .new-tasks_heading
    h2.new-tasks_heading_content.heading
      | EDIT TRAINING

  = form_with  model: @trainig, method: :put, class: "form_class", local: true do |f|
    = f.label :tasks, 'トレーニング名'
    = f.text_field :tasks, value: @training.tasks, id: "tasks"
    = f.label :content, 'トレーニング内容'
    = f.text_area :content, value: @training.content , id: "content"
    = f.label :limit, '日付'
    = f.date_field :limit, value: @training.limit , id: "limit"
    = f.hidden_field :completed, :value => 0, id: 'task_completed'
    = f.submit "更新", class: "submit"

app/app/views/users/mypage.html.slim
section.mypage
  section.mypage__info
    .mypage__info__names
      h2.mypage__info__names__name
        = @user.name
        span.mini
          | さん
    .mypage__info__favorite
      .mypage__info__favorite__texts
        p.mypage__info__favorite__texts__text
          | Favorite
        p.mypage__info__favorite__texts__count
          | 【 
          = @favorite_ranks.length
          |  】
  section.mypage__index
    - @favorite_ranks.each do |favorite_rank|
      = link_to( "#{favorite_rank.itemUrl}",:target=>["_blank"]) do
        .mypage__index__contents
          .mypage__index__contents__content
            .mypage__index__contents__content__images
              = image_tag favorite_rank.mediumImageUrls, class: 'mypage__index__contents__content__images__image'
            .mypage__index__contents__content__texts
              h2.mypage__index__contents__content__texts__text
                = truncate(favorite_rank.itemName, length:60)
              .price_review
                p.mypage__index__contents__content__texts__price
                  span.fee
                    = favorite_rank.itemPrice
                  | 円(税込)
                p.mypage__index__contents__content__texts__review
                  = favorite_rank.reviewAverage
                  span.reviewMax
                    | /5

app/app/views/users/new.html.slim
section.new
  .new__heading
    h2.new__heading__text
      | Sign up
  .errors
    - @user.errors.full_messages.each do|message|
      ul.errors__messages
        li
          = message
  = form_with  model: @user, class: "form_class", local: true do |f|
    = f.label :name, '名前'
    = f.text_field :name
    = f.label :email, 'メールアドレス'
    = f.email_field :email
    = f.label :password, 'パスワード'
    = f.password_field :password
    = f.submit "新規登録", class: "submit"